id: I865C6622
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-05-27T19:00:52.458992'
last_modified: '2022-05-27T19:00:52.459005'
parser: null
source_metadata:
  title: 'MSV 6,02: Vin카tak훮'
  language: bo
  base:
    f0FF4:
      title: Vin카tak훮
      base_file: f0FF4.txt
      order: 1
  chapter_to_tile: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
